/**
 * Versioned roadmap seed.
 *
 * The roadmap content lives in prisma/seed-data/*.json, generated by
 * scripts/parse-roadmap.mjs from the canonical source documents. This script
 * loads that content into the database.
 *
 * Idempotency: every roadmap entity has a stable slug (and therefore a stable
 * id). Seeding upserts by slug, so re-running the seed UPDATES content in place
 * and never deletes a row that user progress points at. That is the mechanism
 * behind the rule that editing master content must not destroy user progress.
 *
 * Run with: npx prisma db seed
 */

import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { PrismaPg } from "@prisma/adapter-pg";
import { Prisma } from "../src/generated/prisma/client.js";
import { PrismaClient } from "../src/generated/prisma/client.js";
import { ACHIEVEMENTS, PROJECT_SEED } from "./seed-content.js";
import { seedInterviewContent } from "./seed-interview.js";

const here = dirname(fileURLToPath(import.meta.url));
const seedDataDir = join(here, "seed-data");

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is not set. See .env.example.");
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString, max: 2 }),
});

const DIFFICULTY_VALUES = new Set(["BEGINNER", "INTERMEDIATE", "ADVANCED", "SENIOR"]);
const ORIGIN_VALUES = new Set(["original", "added", "new", "expanded"]);

function toDifficulty(value: unknown, fallback: string) {
  const candidate = typeof value === "string" ? value.toUpperCase() : "";
  return DIFFICULTY_VALUES.has(candidate) ? candidate : fallback;
}

function toStringArray(value: unknown, limit = 20): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((entry): entry is string => typeof entry === "string")
    .map((entry) => entry.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .slice(0, limit);
}

type Resource = { title: string; url: string; type?: string; note?: string };

/**
 * Interview questions are stored as `{ text, answer }` pairs rather than bare
 * strings, because a question without its model answer is half the value: the
 * whole point is rehearsing the answer, not just recognising the question.
 */
type InterviewQuestion = { text: string; answer: string; derived?: boolean };

function toInterviewQuestions(value: unknown, limit = 20): InterviewQuestion[] {
  if (!Array.isArray(value)) return [];

  return value
    .filter(
      (entry): entry is Record<string, unknown> =>
        typeof entry === "object" && entry !== null,
    )
    .filter((entry) => typeof entry.text === "string" && entry.text.trim().length > 0)
    .slice(0, limit)
    .map((entry) => ({
      text: String(entry.text).replace(/\s+/g, " ").trim(),
      answer: typeof entry.answer === "string" ? entry.answer.replace(/\s+/g, " ").trim() : "",
      // `derived` marks a question the parser generated from a concept list
      // rather than one the source authored. It is kept so the UI can label it.
      ...(entry.derived === true ? { derived: true } : {}),
    }));
}

function toResources(value: unknown, limit = 12): Resource[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter(
      (entry): entry is Record<string, unknown> =>
        typeof entry === "object" && entry !== null,
    )
    .filter((entry) => typeof entry.title === "string" && typeof entry.url === "string")
    .slice(0, limit)
    .map((entry) => ({
      title: String(entry.title).trim(),
      url: String(entry.url).trim(),
      ...(typeof entry.type === "string" ? { type: entry.type.trim() } : {}),
      ...(typeof entry.note === "string" ? { note: entry.note.trim() } : {}),
    }));
}

/**
 * Prerequisite edges are declared in the generated data as topic slugs. They are
 * resolved to ids in a second pass because a prerequisite may live in a group
 * that has not been written yet.
 */
type PendingPrerequisite = { topicSlug: string; prerequisiteSlug: string };

async function main() {
  console.log("Seeding FullStackPath…");

  const files = readdirSync(seedDataDir)
    .filter((file) => /^phase-\d+\.json$/.test(file))
    .sort();

  if (files.length === 0) {
    throw new Error(
      "No phase files found in prisma/seed-data. Run: node scripts/parse-roadmap.mjs",
    );
  }

  const phases = files.map((file) =>
    JSON.parse(readFileSync(join(seedDataDir, file), "utf8")),
  ) as {
    order: number;
    slug: string;
    title: string;
    description: string;
    difficulty: string;
    icon: string | null;
    color: string;
    estimatedHours: number | null;
    objectives: string[];
    groups: {
      slug: string;
      title: string;
      description: string;
      difficulty: string;
      estimatedHours: number | null;
      objectives: string[];
      topics: {
        slug: string;
        title: string;
        description: string;
        difficulty: string;
        estimatedMinutes: number;
        origin: string;
        objectives: string[];
        keyConcepts: string[];
        commonMistakes: string[];
        practiceTasks: string[];
        interviewQuestions: unknown;
        interview: unknown;
        troubleshooting: unknown;
        referenceMarkdown: string | null;
        resources: unknown;
      }[];
    }[];
  }[];

const phaseIdBySlug = new Map<string, string>();
const groupIdBySlug = new Map<string, string>();
// Slugs present in the source this run. Anything in the database but absent
// from here has been removed from the content and must leave the roadmap.
const seededGroupSlugs = new Set<string>();
const seededTopicSlugs = new Set<string>();
  const topicIdBySlug = new Map<string, string>();
  const pendingPrerequisites: PendingPrerequisite[] = [];

  let phaseCount = 0;
  let groupCount = 0;
  let topicCount = 0;

  for (const phase of phases) {
    const difficulty = toDifficulty(phase.difficulty, "BEGINNER");

    const phaseRow = await prisma.phase.upsert({
      where: { slug: phase.slug },
      create: {
        slug: phase.slug,
        title: phase.title,
        description: phase.description,
        order: phase.order,
        difficulty: difficulty as never,
        color: phase.color,
        icon: phase.icon,
        estimatedHours: phase.estimatedHours,
        objectivesJson: phase.objectives ?? [],
        isActive: true,
      },
      update: {
        title: phase.title,
        description: phase.description,
        order: phase.order,
        difficulty: difficulty as never,
        color: phase.color,
        icon: phase.icon,
        estimatedHours: phase.estimatedHours,
        objectivesJson: phase.objectives ?? [],
      },
      select: { id: true },
    });
    phaseIdBySlug.set(phase.slug, phaseRow.id);
    phaseCount += 1;

    for (const [groupIndex, group] of phase.groups.entries()) {
      const groupDifficulty = toDifficulty(group.difficulty, difficulty);

      const groupRow = await prisma.roadmapGroup.upsert({
        where: { slug: group.slug },
        create: {
          phaseId: phaseRow.id,
          slug: group.slug,
          title: group.title,
          description: group.description,
          order: groupIndex + 1,
          difficulty: groupDifficulty as never,
          estimatedHours: group.estimatedHours,
          objectivesJson: group.objectives ?? [],
          isActive: true,
        },
        update: {
          phaseId: phaseRow.id,
          title: group.title,
          description: group.description,
          order: groupIndex + 1,
          difficulty: groupDifficulty as never,
          estimatedHours: group.estimatedHours,
          objectivesJson: group.objectives ?? [],
          isActive: true,
        },
        select: { id: true },
      });
      groupIdBySlug.set(group.slug, groupRow.id);
      seededGroupSlugs.add(group.slug);
      groupCount += 1;

      for (const [topicIndex, topic] of group.topics.entries()) {
        const topicDifficulty = toDifficulty(topic.difficulty, groupDifficulty);
        const estimatedMinutes = Number.isFinite(topic.estimatedMinutes)
          ? Math.min(600, Math.max(5, topic.estimatedMinutes))
          : 60;

        const topicRow = await prisma.topic.upsert({
          where: { slug: topic.slug },
          create: {
            groupId: groupRow.id,
            slug: topic.slug,
            title: topic.title,
            description: topic.description,
            difficulty: topicDifficulty as never,
            order: topicIndex + 1,
            estimatedMinutes,
            objectivesJson: topic.objectives ?? [],
            keyConceptsJson: toStringArray(topic.keyConcepts),
            commonMistakesJson: toStringArray(topic.commonMistakes),
            resourcesJson: toResources(topic.resources),
            practiceJson: toStringArray(topic.practiceTasks),
            interviewQsJson: toInterviewQuestions(topic.interviewQuestions),
            interviewJson: topic.interview ? (topic.interview as never) : Prisma.DbNull,
            troubleshootingJson: topic.troubleshooting ? (topic.troubleshooting as never) : Prisma.DbNull,
            referenceMarkdown: topic.referenceMarkdown ?? null,
            isActive: true,
          },
          update: {
            groupId: groupRow.id,
            title: topic.title,
            description: topic.description,
            difficulty: topicDifficulty as never,
            order: topicIndex + 1,
            estimatedMinutes,
            objectivesJson: topic.objectives ?? [],
            keyConceptsJson: toStringArray(topic.keyConcepts),
            commonMistakesJson: toStringArray(topic.commonMistakes),
            resourcesJson: toResources(topic.resources),
            practiceJson: toStringArray(topic.practiceTasks),
            interviewQsJson: toInterviewQuestions(topic.interviewQuestions),
            interviewJson: topic.interview ? (topic.interview as never) : Prisma.DbNull,
            troubleshootingJson: topic.troubleshooting ? (topic.troubleshooting as never) : Prisma.DbNull,
            referenceMarkdown: topic.referenceMarkdown ?? null,
          },
          select: { id: true },
        });
        topicIdBySlug.set(topic.slug, topicRow.id);
        seededTopicSlugs.add(topic.slug);
        topicCount += 1;

        if (ORIGIN_VALUES.has(topic.origin)) {
          pendingPrerequisites.push({
            topicSlug: topic.slug,
            prerequisiteSlug: "",
          });
        }
      }
    }
  }

  console.log(
    `  roadmap: ${phaseCount} phases, ${groupCount} groups, ${topicCount} topics`,
  );

  // ── Retire groups removed from the content ─────────────────────
  // Archiving, never deleting. Deleting a group cascades to its topics and on
  // to every learner's progress and attempts on them, and the rule is that
  // editing content must not destroy history. An archived group leaves the
  // roadmap but keeps its rows, so restoring it is a single flag flip.
  const archivedGroups = await prisma.roadmapGroup.updateMany({
    where: { slug: { notIn: [...seededGroupSlugs] }, isActive: true },
    data: { isActive: false },
  });
  if (archivedGroups.count > 0) {
    console.log(
      `  archived:  ${archivedGroups.count} group(s) no longer in the source ` +
        `(progress preserved)`,
    );
  }

  // Same reasoning for topics. Fixing how titles are split changes topic slugs,
  // so a corrected parse legitimately retires rows. Deleting them would cascade
  // into every learner's progress and attempts, so they are archived instead and
  // drop out of the roadmap while keeping their history.
  const archivedTopics = await prisma.topic.updateMany({
    where: { slug: { notIn: [...seededTopicSlugs] }, isActive: true },
    data: { isActive: false },
  });
  if (archivedTopics.count > 0) {
    console.log(
      `  archived:  ${archivedTopics.count} topic(s) no longer in the source ` +
        `(progress preserved)`,
    );
  }

  // ── Project milestones ────────────────────────────────────────
  let projectCount = 0;
  for (const project of PROJECT_SEED) {
    await prisma.project.upsert({
      where: { slug: project.slug },
      create: {
        slug: project.slug,
        title: project.title,
        description: project.description,
        order: project.order,
        difficulty: project.difficulty as never,
        stackJson: project.stack,
        objectivesJson: project.objectives,
        checklistJson: project.checklist,
        relatedTopicSlugsJson: project.relatedTopicSlugs,
        estimatedHours: project.estimatedHours,
      },
      update: {
        title: project.title,
        description: project.description,
        order: project.order,
        difficulty: project.difficulty as never,
        stackJson: project.stack,
        objectivesJson: project.objectives,
        checklistJson: project.checklist,
        relatedTopicSlugsJson: project.relatedTopicSlugs,
        estimatedHours: project.estimatedHours,
      },
    });
    projectCount += 1;
  }
  console.log(`  projects: ${projectCount}`);

  // ── Achievements ──────────────────────────────────────────────
  for (const achievement of ACHIEVEMENTS) {
    await prisma.achievement.upsert({
      where: { slug: achievement.slug },
      create: {
        slug: achievement.slug,
        name: achievement.name,
        description: achievement.description,
        icon: achievement.icon,
        criteriaJson: achievement.criteria,
      },
      update: {
        name: achievement.name,
        description: achievement.description,
        icon: achievement.icon,
        criteriaJson: achievement.criteria,
      },
    });
  }
  console.log(`  achievements: ${ACHIEVEMENTS.length}`);

  // ── Interview question bank and practice blocks ──────────────
  const interview = await seedInterviewContent(phases);
  console.log(
    `  interview: ${interview.questionCount} questions (${interview.questionsWithAnswers} with a model answer), ` +
      `${interview.blockCount} practice blocks with ${interview.blockItemCount} items`,
  );
  if (interview.prunedQuestions > 0 || interview.prunedBlocks > 0) {
    console.log(
      `  pruned:    ${interview.prunedQuestions} questions, ${interview.prunedBlocks} blocks ` +
        `that are no longer in the source`,
    );
  }

  // ── Summary ───────────────────────────────────────────────────
  const [storedPhases, storedGroups, storedTopics] = await Promise.all([
    prisma.phase.count(),
    prisma.roadmapGroup.count(),
    prisma.topic.count(),
  ]);

  console.log(
    `Done. Database now holds ${storedPhases} phases / ${storedGroups} groups / ${storedTopics} topics.`,
  );
  console.log(
    "Existing user progress was left untouched: roadmap rows were upserted by slug, never deleted.",
  );
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });